default_stages: [commit, push]
exclude: ^fact_helper_file/bin/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
        args: [--maxkb=10000]

    -   id: check-json

    -   id: check-merge-conflict

    -   id: check-yaml

    -   id: end-of-file-fixer
        types: [python]

    -   id: fix-encoding-pragma
        args: [--remove]

    -   id: file-contents-sorter
        files: .gitignore|_list.txt

    -   id: forbid-new-submodules

    -   id: no-commit-to-branch

    -   id: pretty-format-json
        args: [--autofix]

    -   id: trailing-whitespace
        types: [python]

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.5.6'
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
    - id: ruff-format
