dist: xenial
language: python
python:
  - 3.5
  - 3.6
install:
  - python3 setup.py build
  - python3 setup.py install
  - pip3 install -r requirements-dev.txt
  - pip3 install codecov
script:
  - py.test --cov=./fact_helper_file
after_success:
- codecov
